CREATE TABLE TOPIC(
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	LABEL VARCHAR(200)
)

CREATE TABLE USERS(
	ID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	USERNAME VARCHAR(200),
	EMAIL VARCHAR(200)
)

CREATE TABLE SUBSCRIPTION (
	TOPIC_ID INT,
	USER_ID INT,
	FOREIGN KEY(TOPIC_ID) REFERENCES TOPIC (ID),
	FOREIGN KEY(USER_ID) REFERENCES USERS (ID)
)