INSERT TOPIC(LABEL) VALUES('facturation');
INSERT TOPIC(LABEL) VALUES('facturation.societe1');
INSERT TOPIC(LABEL) VALUES('facturation.societe2');
INSERT TOPIC(LABEL) VALUES('helpdesk');
INSERT TOPIC(LABEL) VALUES('helpdesk.societe1');
INSERT TOPIC(LABEL) VALUES('helpdesk.societe2');

INSERT USERS(USERNAME, EMAIL) VALUES('Remy Girodon', 'rgirodon@sqli.com');
INSERT USERS(USERNAME, EMAIL) VALUES('Nicolas Moret', 'nmoret@sqli.com');
INSERT USERS(USERNAME, EMAIL) VALUES('Matthis Duclos', 'mduclos@sqli.com');

INSERT SUBSCRIPTION(TOPIC_ID, USER_ID) VALUES(1, 1);
INSERT SUBSCRIPTION(TOPIC_ID, USER_ID) VALUES(2, 1);
INSERT SUBSCRIPTION(TOPIC_ID, USER_ID) VALUES(3, 2);
INSERT SUBSCRIPTION(TOPIC_ID, USER_ID) VALUES(4, 2);
INSERT SUBSCRIPTION(TOPIC_ID, USER_ID) VALUES(5, 3);
INSERT SUBSCRIPTION(TOPIC_ID, USER_ID) VALUES(6, 3);